version: "3.8"

networks:
  passphrasex:
    driver: bridge

volumes:
    db_data: {}
    certificates: {}
    api_target: {}

services:
    api:
        build:
            context: ..
            dockerfile: ./api/Dockerfile
        image: api
        container_name: passphrasex-api
        hostname: api
        expose:
            - "3000"
        networks:
            - passphrasex
        depends_on:
            - db
        environment:
            - MONGODB_URI=mongodb://db:27017/api
        volumes:
            - api_target:/usr/src/api/target
    db:
        image: mongo
        container_name: passphrasex-db
        expose:
            - "27017"
        networks:
            - passphrasex
        volumes:
            - db_data:/data/db
    nginx:
        build:
            context: ./nginx
            dockerfile: ./Dockerfile
        container_name: passphrasex-nginx
        ports:
            - "80:80"
            - "443:443"
        networks:
            - passphrasex
        volumes:
            - certificates:/etc/letsencrypt/live/passphrasex.srosati.xyz
        environment:
            - DOMAIN=passphrasex.srosati.xyz
            - EMAIL=srosati@itba.edu.ar
        depends_on:
            - api



