version: "3.8"

networks:
  passphrasex:
    driver: bridge

volumes:
    db_data: {}
    certificates: {}

services:
    api:
        build:
            context: ..
            dockerfile: ./api/Dockerfile
        image: api
        container_name: passphrasex-api
        hostname: api
        expose:
            - "3000"
        networks:
            - passphrasex
        depends_on:
            - db
        environment:
            - MONGODB_URI=mongodb://db:27017/api
    db:
        image: mongo
        container_name: passphrasex-db
        expose:
            - "27017"
        networks:
            - passphrasex
        volumes:
            - db_data:/data/db
    nginx:
        image: nginx:alpine
        container_name: passphrasex-nginx
        ports:
            - "80:80"
            - "443:443"
        networks:
            - passphrasex
        volumes:
#            - /private/etc/ssl/localhost:/etc/ssl/localhost:ro
            - certificates:/etc/ssl/localhost
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - api
            - certbot
    certbot:
        image: certbot/certbot:latest
        container_name: passphrasex-certbot
        volumes:
            - certificates:/var/www/certbot
        command:
            - certonly
            - --webroot
            - --webroot-path=/var/www/certbot
            - --agree-tos
            - --no-eff-email
            - --email=srosati@itba.edu.ar
            - --non-interactive
            - -d passphrasex.srosati.xyz



