# Based on https://github.com/actions-rs/meta/blob/master/recipes/quickstart.md
#
# While our "example" application has the platform-specific code,
# for simplicity we are compiling and testing everything on the Ubuntu environment only.
# For multi-OS testing see the `cross.yml` workflow.

on: [push, pull_request]

name: API

jobs:
  test:
    name: Check & Test
    runs-on: ubuntu-latest
    steps:
      - name: Install tools
        run: apt-get update && apt-get install -y libssl-dev pkg-config curl build-essential

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.6.0

      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Run cargo check
        working-directory: api
        run: cargo check --all

      - name: Run cargo test
        working-directory: api
        run: cargo test --all